### ISSUE TITLE
Faturas

### ISSUE THREAD

**Issue by GustavoSimes** [GustavoSimes/oficina_automovel#1]
elabora o código no ficheiro faturas.py

**Comment by AbelFDias** [comment]
ok vou ja

**Comment by GustavoSimes** [comment]
git fetch origin
git checkout faturas-abel

**Comment by GustavoSimes** [comment]
Completa todos os TO DO'S do ficheiro faturas.py

**Comment by AbelFDias** [comment]
é necessário acabar o ficheiro clientes.py antes de fazer o faturas.py

**Comment by GustavoSimes** [comment]
ok completa então o clientes.py, vou criar outro issue para isso

**Comment by GustavoSimes** [comment]
Abel!! Oh palhaço toca a trabalhar, ainda não acabaste o código das faturas, toca a andar seu ganda atum!!

**Comment by GustavoSimes** [comment]
Simão se quiseres ajudar o Abel com este problema podes por as mãos à obra, acho que ele agradece a tua ajuda

**Comment by GustavoSimes** [comment]
Ainda falta tratar deste issue por favor despachem-se

**Comment by AbelFDias** [comment]
falta coisas em faturas.py?
nao vejo nenhum todo
