### ISSUE TITLE
Wiki-biki

### ISSUE THREAD

**Issue by GustavoSimes** [GustavoSimes/oficina_automovel#6]
OH Abel!! Seu grande poste elétrico da MEO! A wiki que criaste está muito fraca, peço que elabores a mesma imediatamente sem qualquer atraso. Obrigado e mãos à obra Atum

**Comment by AbelFDias** [comment]
ok

**Comment by AbelFDias** [comment]
penso que terminei a wiki
peço que vossa excelência possa checar

**Comment by GustavoSimes** [comment]
não és documenter nenhum belhote mas pronto
