### ISSUE TITLE
README

### ISSUE THREAD

**Issue by GustavoSimes** [GustavoSimes/oficina_automovel#7]
Abel seu atum flutuante! Faz mazé o readme também, espero bem que tenhas a noção que um elefante grávido cozinha mais ADC do que tu, então toca a andar e faz o readme também! Cumprimentos Gustavo

**Comment by AbelFDias** [comment]
sim senhor chefe é pra já senhor chefe, espero que o meu salário esteja na minha conta nos proximos 3 dias uteis senhor chefe👀

Cumprimentos ao chefe
-Abel Dias

**Comment by GustavoSimes** [comment]
A nossa ideia é por uma imagem de uma oficina e um titulo com o nome da nossa ofivina que é "Oficina Autimóvel SAG"
dps metes umas cenas atoa tipo os nossos discords ou insta sei la, e dps começas a intodução ao trabalho, a aplicação né, falas do que é que foi feito e para que serve depois falas dos contéudos e dps agradecimentos e sítios onde fomos buscar imformação para conseguir fazer o trabalho

**Comment by GustavoSimes** [comment]
https://github.com/facebook/docusaurus#readme
Aqui está um exemplo para te baseares

**Comment by AbelFDias** [comment]
gostaria de orientações quanto ao tema "como começar"

**Comment by GustavoSimes** [comment]
primeiro de tudo nós somos a oficina automóvel SAG

**Comment by GustavoSimes** [comment]
chama esse como começar de como usar e deixa como está

**Comment by GustavoSimes** [comment]
e depois cria uma introdução para dizer o objetivo e o que fizemos

**Comment by AbelFDias** [comment]
introdução e tal deveria ser na wiki, não?

**Comment by GustavoSimes** [comment]
não, deve ser no readme, apresenta o trabalho com a introdução

**Comment by AbelFDias** [comment]
penso que está tudo, qualquer coisa, abre de novo esta issue

**Comment by GustavoSimes** [comment]
Muito bom trabalho, obrigado
